KoiPond/Controllers/DuAnsController.cs
using KoiPond.Repositories.Models;
using KoiPond.Services;
using KoiPond.Services.Services;
using Microsoft.AspNetCore.Mvc;

namespace KoiPond.Controllers
{
    public class DuAnsController : Controller
    {
        private readonly IDuAnService _duAnService;

        public DuAnsController(IDuAnService duAnService)
        {
            _duAnService = duAnService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _duAnService.GetAllDuAnAsync();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var sanPham = await _duAnService.GetDuAnByIdAsync(id.Value);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DuAns/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TenDuAn,MoTa,UuDiem,KichThuoc,VatLieu,SoLuongCa,ThietKe,HinhAnh")] DuAn duAn, IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                await _duAnService.AddDuAnAsync(duAn, uploadedFile);
                return RedirectToAction("Index");
            }
            return View(duAn);
        }

    }
}

KoiPond/Controllers/SanPhamsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KoiPond.Repositories.Models;
using KoiPond.Services.Services;
using Microsoft.AspNetCore.Authorization;

namespace KoiPond.Controllers
{
    /*
     * Old contrller
     *public class SanPhamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SanPhamsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SanPhams
        public async Task<IActionResult> Index()
        {
            return View(await _context.SanPhams.ToListAsync());
        }

        // GET: SanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .FirstOrDefaultAsync(m => m.MaSanPham == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSanPham,TenSanPham,DanhMuc,MoTaSanPham,Gia,SoLuongTrongKho,DuongDanFileMau,NgayTao,NgayCapNhat")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSanPham,TenSanPham,DanhMuc,MoTaSanPham,Gia,SoLuongTrongKho,DuongDanFileMau,NgayTao,NgayCapNhat")] SanPham sanPham)
        {
            if (id != sanPham.MaSanPham)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSanPham))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .FirstOrDefaultAsync(m => m.MaSanPham == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham != null)
            {
                _context.SanPhams.Remove(sanPham);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanPhamExists(int id)
        {
            return _context.SanPhams.Any(e => e.MaSanPham == id);
        }
    }
    */
    [Authorize(Roles = "Admin, Manager")]

    public class SanPhamsController : Controller
    {
        private readonly ISanPhamService _service;

        public SanPhamsController(ISanPhamService service)
        {
            _service = service;
        }

        // GET: SanPhams
        public async Task<IActionResult> Index()
        {
            var sanPhams = await _service.GetAllSanPhamsAsync();
            return View(sanPhams);
        }

        // GET: SanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var sanPham = await _service.GetSanPhamByIdAsync(id.Value);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SanPhams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSanPham,TenSanPham,DanhMuc,MoTaSanPham,Gia,SoLuongTrongKho,DuongDanFileMau,NgayTao,NgayCapNhat")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                await _service.AddSanPhamAsync(sanPham);
                return RedirectToAction(nameof(Index));
            }
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var sanPham = await _service.GetSanPhamByIdAsync(id.Value);
            if (sanPham == null)
            {
                return NotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSanPham,TenSanPham,DanhMuc,MoTaSanPham,Gia,SoLuongTrongKho,DuongDanFileMau,NgayTao,NgayCapNhat")] SanPham sanPham)
        {
            if (id != sanPham.MaSanPham)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateSanPhamAsync(sanPham);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _service.SanPhamExistsAsync(sanPham.MaSanPham))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var sanPham = await _service.GetSanPhamByIdAsync(id.Value);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteSanPhamAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }

}

KoiPond/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using KoiPond.Repositories.Models;
using KoiPond.Repositories.ViewModels;

namespace KoiPond.Controllers
{
    public class UsersController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;
        public UsersController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            this.roleManager = roleManager;

            this.userManager = userManager;
        }
        [HttpGet]
        public IActionResult ListUsers(string searchString, string currentFilter)
        {
            if (searchString != null)
            {
                
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var users = userManager.Users;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => s.UserName.Contains(searchString));
            }

            return View(users);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("Error");
            }

            // GetClaimsAsync retunrs the list of user Claims
            var userClaims = await userManager.GetClaimsAsync(user);
            // GetRolesAsync returns the list of user Roles
            var userRoles = await userManager.GetRolesAsync(user);

            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                Roles = userRoles
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.Id} cannot be found";
                return View("Error");
            }
            else
            {
                user.Email = model.Email;
                user.UserName = model.UserName;

                var result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("Error");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListUsers");
            }
        }
    }
}

KoiPond/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link asp-append-version="true" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">
    <link asp-append-version="true" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link asp-append-version="true" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link asp-append-version="true" href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link asp-append-version="true" href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
    <link asp-append-version="true" href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link asp-append-version="true" href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link asp-append-version="true" href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <header>
        <!-- Navbar Start -->
        <div class="container-fluid sticky-top bg-dark bg-light-radial shadow-sm px-5 pe-lg-0">
            <nav class="navbar navbar-expand-lg bg-dark bg-light-radial navbar-dark py-3 py-lg-0">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand d-flex align-items-center">
                    <i class="bi bi-bricks text-primary display-1 me-3"></i>
                    <div>
                        <h1 class="m-0 display-4 text-uppercase text-white">KOI POND</h1>
                        <h2 class="m-0 text-uppercase text-white-50 fs-4">Construction Ordering System</h2>
                    </div>
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0">
                        <a asp-action="Index" asp-controller="Home" class="nav-item nav-link">Trang chủ</a>


                        @if (!User.IsInRole("Admin") && !User.IsInRole("Manager"))
                        {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Giới thiệu</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="Home" asp-action="About" class="dropdown-item">Giới thiệu</a>
                                    <a asp-controller="Duans" asp-action="Index" class="dropdown-item">Dự án</a>
                                </div>
                            </div>

                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Dịch vụ</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="YeuCauThiCongs" asp-action="Create" class="dropdown-item">Thi công</a>
                                    <a asp-controller="YeuCauDichVus" asp-action="Create" class="dropdown-item">Chăm sóc</a>
                                </div>
                            </div>

                            <a asp-action="Create" asp-controller="DanhGiaPhanHois" class="nav-item nav-link">Đánh giá</a>
                        }


                        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                        {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Quản trị</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="NhanViens" asp-action="Index" class="dropdown-item">Nhân viên</a>
                                    <a asp-controller="KhachHangs" asp-action="Index" class="dropdown-item">Khách hàng</a>
                                    <a asp-controller="SanPhams" asp-action="Index" class="dropdown-item">Sản phẩm</a>
                                    <a asp-controller="DuAns" asp-action="Create" class="dropdown-item">Dự án</a>
                                    <a asp-controller="DanhGiaPhanHois" asp-action="Index" class="dropdown-item">Feedback</a>
                                    <a asp-controller="Roles" asp-action="Listroles" class="dropdown-item">Quyền</a>
                                    <a asp-controller="Users" asp-action="ListUsers" class="dropdown-item">Tài khoản</a>
                                </div>
                            </div>
                        }

                        @if (User.IsInRole("Staff") || User.IsInRole("Manager") || User.IsInRole("Admin"))
                        {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Xác nhận yêu cầu</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="YeuCauThiCongs" asp-action="Index" class="dropdown-item">Thi công</a>
                                    <a asp-controller="YeuCauDichVus" asp-action="Index" class="dropdown-item">Chăm sóc</a>
                                </div>
                            </div>
                        }

                        @if (User.IsInRole("Customer") || User.IsInRole("Guest"))
                        {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Yêu cầu của tôi</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="YeuCauThiCongs" asp-action="Index" class="dropdown-item">Thi công</a>
                                    <a asp-controller="YeuCauDichVus" asp-action="Index" class="dropdown-item">Chăm sóc</a>
                                </div>
                            </div>

                        }

                        @if (signInManager.IsSignedIn(User) && User.Identity != null)
                        {
                            <form method="post" asp-action="logout" asp-controller="account" class="d-none d-lg-block">
                                <button type="submit" class="nav-item nav-link bg-primary text-white ms-3">
                                    Logout, @User.Identity.Name
                                </button>
                            </form>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Login" class="nav-item nav-link bg-primary text-white ms-3 d-none d-lg-block">
                                Đăng nhập <i class="bi bi-arrow-right"></i>
                            </a>
                        }
                    </div>
                </div>
            </nav>
        </div>
        <!-- Navbar End -->
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer Start -->
    <div class="footer container-fluid position-relative bg-dark bg-light-radial text-white-50 py-6 px-5">
        <div class="row g-5">
            <div class="col-lg-6 pe-lg-5">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand d-flex align-items-center">
                    <i class="bi bi-bricks text-primary display-1 me-3"></i> <!-- Make icon larger with display-1 -->
                    <div>
                        <h1 class="m-0 display-4 text-uppercase text-white">KOI POND</h1>
                        <h2 class="m-0 text-uppercase text-white-50 fs-4">Construction Ordering System</h2> <!-- Smaller font for subtitle -->
                    </div>
                </a>
                <p>Chúng tôi luôn hân hành được phục vụ mọi như cầu của quý khách.!</p>
                <p><i class="fa fa-map-marker-alt me-2"></i>So 70, duong To Ky, phuong Tan Chanh Hiep, Quan 12, Tp. Ho Chi Minh</p>
                <p><i class="fa fa-phone-alt me-2"></i>+012 345 67890</p>
                <p><i class="fa fa-envelope me-2"></i>NHOMF@example.com</p>
                <div class="d-flex justify-content-start mt-4">
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-0 me-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-0 me-2" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-0 me-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-0" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <div class="col-lg-6 ps-lg-5">
                <div class="row g-5">
                    <div class="col-sm-6">
                        <h4 class="text-white text-uppercase mb-4">Liên Kết Nhanh</h4>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right me-2"></i>Trang chủ</a>
                            <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right me-2"></i>Giới thiệu</a>
                            <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right me-2"></i>Dịch vụ của chúng tôi</a>
                            <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right me-2"></i>Gặp gỡ nhóm</a>
                            <a class="text-white-50" href="#"><i class="fa fa-angle-right me-2"></i>Liên hệ với chúng tôi</a>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <h4 class="text-white text-uppercase mb-4">Liên Kết Phổ Biến</h4>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right me-2"></i>Trang chủ</a>
                            <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right me-2"></i>Giới thiệu</a>
                            <a class="text-white-50" href="#"><i class="fa fa-angle-right me-2"></i>Liên hệ với chúng tôi</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark bg-light-radial text-white border-top border-primary px-0">
        <div class="d-flex flex-column flex-md-row justify-content-between">
            <div class="py-4 px-5 text-center text-md-start">
                <p class="mb-0">&copy; <a class="text-primary" href="#">KoiPond</a>. Bảo lưu mọi quyền..</p>
            </div>
            <div class="py-4 px-5 bg-primary footer-shape position-relative text-center text-md-end">
                <p class="mb-0">Thiết kế bởi <a class="text-dark">NHOM F</a></p>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script asp-append-version="true" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script asp-append-version="true" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    <script asp-append-version="true" src="~/lib/easing/easing.min.js"></script>
    <script asp-append-version="true" src="~/lib/waypoints/waypoints.min.js"></script>
    <script asp-append-version="true" src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script asp-append-version="true" src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script asp-append-version="true" src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script asp-append-version="true" src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script asp-append-version="true" src="~/lib/isotope/isotope.pkgd.min.js"></script>
    <script asp-append-version="true" src="~/lib/lightbox/js/lightbox.min.js"></script>

    <!-- Template Javascript -->
    <script asp-append-version="true" src="~/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>